### ISSUE TITLE
Log lines are not inserted into log files

### ISSUE THREAD

**Issue by erikzenker** [palavatv/signaltower#12]
Calls to the logger do not insert log lines into the log file.

**Comment by farao** [comment]
The problem is not that logging output is not printed normally but that it is not printed when doing a release (e.g. `mix release staging`) and then start it as a daemon (`_build/dev/rel/staging/bin/staging daemon`) - it remains to be researched how to get the logging output when started as a release daemon.

**Comment by farao** [comment]
The logs for releases when run in daemon mode are deeply nested in the _build directory for releases, but they're there, so I'm closing this ticket
